name: Close Stale Issues and Show OS Name
on: [push]
    # schedule:
    #   - cron: '30 1 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 1 days with no activity.'
        stale-issue-label: 'no-issue-activity'
        days-before-issue-stale: 1


  Show OS Name:
    runs-on: ubuntu-latest
    steps:
      - name: Show the Name of the OS running
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
